
stages:
  - build
  - test
  - deploy

variables:
  # Definiere die Node.js Version, die verwendet werden soll
  NODE_VERSION: "22.5.1"

cache:
  paths:
    - node_modules/

before_script:
  # Installiere Node.js
  - apt-get update -y
  - apt-get install -y curl
  - curl -sL https://deb.nodesource.com/setup_$NODE_VERSION.x | bash -
  - apt-get install -y nodejs

build:
  stage: build
  script:
    - npm install
    - npm run build

#test:
#  stage: test
#  script:
#    - npm run test

deploy:
  stage: deploy
  script:
    - echo "Deployment Schritt (abhängig von deinem Deployment-Prozess)"
  only:
    - master

deploy-staging:
  extends: deploy
  allow_failure: true
  variables:
    NODE_ENV: staging
  script:
    - echo "Deploying to $CI_ENVIRONMENT_NAME"
    - echo "Making actions to deploy to staging"
    - echo "Deployed to $CI_ENVIRONMENT_NAME"


